spring:
  thymeleaf:
    cache: false
  mail:
    host: smtp.163.com
    username: xxx
    password: xxx
    port: 465
    properties:
      from: xxx
      mail:
        smtp:
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/management?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: xxx
    password: xxx
    hikari:
      pool-name: DateHikariCP
      minimum-idle:  5
      idle-timeout:  180000
      maximum-pool-size: 10
      auto-commit: true
      max-lifetime: 180000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  data:
    redis:
      port: 6379
      host: xxx
      database: 0
      timeout: 10000ms
      password: xxx
      lettuce:
        pool:
          max-active: 8
          max-wait: 10000ms
          max-idle: 200
          min-idle: 5


logging:
  level:
    com.pineapple.management: debug
